### ISSUE TITLE
Different chart types

### ISSUE THREAD

**Issue by sandikbarr** [PRX/metrics.prx.org#108]
The user can select from 4 different chart types

@farski I'm pretty unclear about what these different chart types do in the new design. 
* The one shown you said is like what we are currently doing but just not an area chart. What is the data? There's only the single line, so is that at the podcast level?
* The next chart button to the right, the squiggly with a line through it. What does that represent? Is that the selected episodes, one line per episode? These are not stacked lines are they?
* The next chart button, the area. Is that the stacked area chart that we are currently doing? Are there any changes to it? Is it only the episodes? Does it include the podcast? Can the user remove the total podcast area from the chart and only show episode data?
* The next one that looks like a horizontal bar chart. Is that a stacked bar chart? Is that like what we're doing now when there are less than 4 datapoints in an area chart, or is this something different? Same questions as the stacked area, is this the podcast + selected episodes?

**Comment by farski** [comment]
I stole a lot of this behavior from the YouTube analytics UI, because I tend to like how they do the chart/table parts, and range/interval. Some of the other stuff feels a little too obtuse and adds confusing layers. But if you want kind of get a live demo that's a good place to look. That being said, your assumptions are pretty close, at least as far as how they do it (which I'm not married to, but don't hate as a starting point)

**Line chart:** A single line that reflects all data from the selected range, broken down by interval. This means that the chart does not always match 1:1 with the table, as they page their tables to a max of 25 lines. So, eg, if the selected range is 365 days and the interval is daily, the chart will have 365 points, even though only 25 are currently visible in the chart

**Multi-line chart:** Covers the entire range, broken down by selected interval, but only a maximum of five series are ever shown in the chart. By default they show the first five, based on how the chart is sorted (ie the first five when sorted by views could be different than the first five when sorted by watch time). Once you start to explicitly select individual episodes from the table, only selected series show up. Whether it's showing the default or selected, the table has a color swatch that reflects the line in the chart. 

**Stacked area chart:** Works basically the same as the multi-line, except it's stacked. YouTube does not include totals, I suspect since the line chart already includes that data. Some people seemed to like having that relative comparison, so maybe we continue to offer that as an option

**Bar chart:** This one works differently. They again do a limit of five, follow the same default/selection method as above. But it doesn't break the data down by selected interval. Essentially this is a rollup of the entire selected range per episode. One bar per episode, the value equal to the number total in the range for that episode. This essentially matches the per-video totals that they show in table, since they don't do interval values in the chart.

**Comment by sandikbarr** [comment]
> first five when sorted by views could be different than the first five when sorted by watch time
I dont think we can really show playback with downloads in the same chart/table since the source data is not one for one

**Comment by sandikbarr** [comment]
It seems odd like an odd limitation for charted data to only be up to 5 series but show 8 series in the table

**Comment by farski** [comment]
The limit of 5 in the table I suspect is just a somewhat arbitrary decision based on how many lines or stacks you can get in there before it gets too crowded. I think five to 10 was about what had come up during the design review, so something in that range feels like a good amount to start with. I'm not sure what a good size for the table is. The 8 rows that were there in the mockup weren't meant as any sort of hard limit.

**Comment by sandikbarr** [comment]
We decided that for downloads the most useful chart types would be the single line podcast chart, the multi-line episode chart, and the stacked area (with the option to toggle charting of the podcast total/all others)
