### ISSUE TITLE
date range preset quick selector

### ISSUE THREAD

**Issue by sandikbarr** [PRX/metrics.prx.org#122]
The date range preset selector includes a set of useful/frequently used date ranges that can be applied instantly. The dropdown includes a text description of each range (eg Last month), and a bit of informational date data so it's always obvious what the range actually represents (ie, for This week it includes the fact that we start weeks on a given day of the week). The options are loosely arranged into logical groupings.

The text in the control button includes just the short text description of the current range. In cases where the current range doesn't match one of the options, the button would indicate the actual current range (by date, eg Nov 13, 2017 – Nov 18, 2017).

The options will be the ones shown in the attached image.
![image](https://user-images.githubusercontent.com/2250413/33907964-8669a53c-df4c-11e7-931a-575a192e6487.png)

(Also note that a single select dropdown should not have checkboxes)

**Comment by farski** [comment]
I wouldn't necessarily use the options that were in the mockup as the definitive selection that makes it into this first revision. I included things like _Last 365 days_ because the pattern was consistent, but I know we don't have data going back that far, so idk it makes sense to include out of the gate
