### ISSUE TITLE
Date range summary

### ISSUE THREAD

**Issue by sandikbarr** [PRX/metrics.prx.org#134]
A summary of the date range shown in the chart will appear below the menu bar and above the chart titled "IN THIS RANGE" listing the begin and end dates and how many days.

@farski are the dates actually formatted DATE Month YEAR in this summary? (but we're formatting numeric Month Date elsewhere) Commas or no commas?

@farski will the `(22 days)` part of the summary always be days or will it be the number of hours, weeks, or months when those intervals are shown?

**Comment by farski** [comment]
I'm not married to any particular date format. Feel free to play with different options in different displays contexts and see what feels best.

I think having it stay days makes sense for now, since they're the biggest unit of time that will never get broken up by a range selection. Something to revisit in the future, or even just drop if it ends up not feeling all that useful.

**Comment by sandikbarr** [comment]
Our intervals are not actually broken up by range selections (except for the last partial interval including the current hour/day/week/month). When dates are selected that don't match the beginning or end of weeks or months, the date range is spread out to the beginning and end of the week/month.

**Comment by farski** [comment]
Oh yeah, I see that now. Hmm. That leads to some, in my opinion, unexpected behavior for the control elements (preset disappearing, selected dates not actually being honored when hitting Apply, etc).

I thought I had made a ticket about this back even before the redesign, but I can't find it now, so perhaps I just said it in a meeting. How I've seen this done in other systems is that the date range selection happens irrespective of grouping. Essentially it's a two stage process: first a range is determined, and then the data from that range is sorted into buckets based on the selected interval.

For example, if the range is Dec 31 to Dec 31, and the interval is Months, we'd end up with one bucket that only has the data from Dec 31 (and would be a single point on the line graph, or one point per episode on the others). If the range is Dec 31 to Jan 1 with a Month interval, we'd get two buckets, one for December with only the 31st's data, and one for Jan with only the 1st's data. (two points on the line graph, two points per episode on the multi series charts).

This can lead to some slightly more obtuse data presentations, but it does allow the user to decide exactly which data they want to see. If they want to use a range that is pegged to the calendar, they can, and if they want to aggregate a more arbitrary range they still have the option to do that.

I lean towards that type of system since it retains flexibility, and I don't think most people will stumble into the more confusing scenarios unless they do it on purpose. It also keeps the UI much more consistent.

**Comment by sandikbarr** [comment]
The choice to spread the dates wasn't exactly a UI choice. The UI choice was to make the dates match the data since that's how the data rollups work. We don't have a partial month interval containing just the Dec 31st data as a rollup option.

**Comment by sandikbarr** [comment]
--> The date format will be Mon D, YYYY (`MMM D, YYYY` with moment)
