### ISSUE TITLE
Entering dates into adv. selector can behave strangely

### ISSUE THREAD

**Issue by farski** [PRX/metrics.prx.org#148]
![image](https://user-images.githubusercontent.com/3483/34743207-f84fb798-f556-11e7-9ea8-a41410f8220e.png)

When I type a date into here it seems like it always loses a day. Eg, if I type in 2017-12-29, as soon as I type the `9` it becomes 2017-12-28.

**Comment by pkarman** [comment]
@sandikbarr can you duplicate and estimate please?

**Comment by sandikbarr** [comment]
seems like a problem with UTC support on input

**Comment by pkarman** [comment]
@sandikbarr will this be addressed by or impacted by the castle work @cavis is doing?

**Comment by sandikbarr** [comment]
No, I think it's a problem with the UTC support I added to the datepicker. (It's kind of convoluted because the underlying library really wants to use local at 0:0:0.) I don't know how many people will actually be typing into the date picker inputs, so this may not need to be fixed before beta release and could get a fix slipped in after.

**Comment by pkarman** [comment]
ok thanks. downgrading to medium so we can bump it.
