### ISSUE TITLE
X axis tick marks are displayed inconsistently

### ISSUE THREAD

**Issue by farski** [PRX/metrics.prx.org#176]
When the chart range gets somewhat large, the tick marks on the X axis seem to be placed unevenly. Also there are probably more of them than necessary.

They seem to cluster up in the middle, and be more sparse on the extremes.

![image](https://user-images.githubusercontent.com/3483/35162786-5d1a303c-fd12-11e7-9e39-aad897370264.png)

Haven't dug in enough to know if it's just a weird rendering thing, or there are actually more of them

**Comment by sandikbarr** [comment]
Messing with the charts today, so I tried some things with fit 

If true (default), the ticks will be positioned nicely. If false, the ticks will be positioned according to x value of the data points.
http://c3js.org/reference.html#axis-x-tick-fit

For reference, here is the chart with updates from #159 and #147
<img width="879" alt="screen shot 2018-02-01 at 4 15 36 pm" src="https://user-images.githubusercontent.com/2250413/35706564-ddf10d9e-076b-11e8-8ae7-8d65efd2dd42.png">

This is fit set to false. 
<img width="880" alt="screen shot 2018-02-01 at 4 18 52 pm" src="https://user-images.githubusercontent.com/2250413/35706569-e547095e-076b-11e8-9de3-595d9fb33325.png">

Tick fit seems to just give us only first of the month ticks until it's just a few months apart

<img width="875" alt="screen shot 2018-02-01 at 4 24 22 pm" src="https://user-images.githubusercontent.com/2250413/35706713-6b6cff20-076c-11e8-8ea9-6f20a1ffadb7.png">

There does seem to be a small range where there are too many tick labels, quite a few more than would be there by default. It spreads out pretty well otherwise except in this weird range of ~30-37 ticks. It makes some interesting choices with what tick texts to show with the January boundaries here:
<img width="876" alt="screen shot 2018-02-01 at 4 35 18 pm" src="https://user-images.githubusercontent.com/2250413/35707104-0e7b97ca-076e-11e8-9bac-d5711b8c9799.png">

To compare what we have with the default ticks in that range:
<img width="875" alt="screen shot 2018-02-01 at 4 36 48 pm" src="https://user-images.githubusercontent.com/2250413/35707129-2f216d10-076e-11e8-9b16-544462702857.png">

Seems like we might also be able to use tick culling and/or tick count to deal with that weird range where the texts overlap with fit=false. Culling is already the default for these timeseries charts, but it doesn't seem to getting the max correct, which seems to be a common problem people have complained about with formatting the ticks.
http://c3js.org/reference.html#axis-x-tick-culling-max
http://c3js.org/reference.html#axis-x-tick-count

**Comment by sandikbarr** [comment]
We will use fit and see if culling improves things and include in beta. 👍
