### ISSUE TITLE
Tweak area chart styles

### ISSUE THREAD

**Issue by farski** [PRX/metrics.prx.org#184]
Cont. of #159

**Comment by farski** [comment]
Currently the dots show up sporadically, so I think we drop them for now

![image](https://user-images.githubusercontent.com/3483/35395204-b1339eac-01b7-11e8-950c-c93ca011a3ab.png)

**Comment by farski** [comment]
The vertical guidelines are getting occluded by the chart areas in our graphs

![image](https://user-images.githubusercontent.com/3483/35395543-a644d0d2-01b8-11e8-87a2-5a21e4515103.png)

But they're entirely visible in the demos http://c3js.org/samples/chart_area_stacked.html

Can we get them to be visible in the same way?

**Comment by pkarman** [comment]
@sandikbarr to investigate

**Comment by sandikbarr** [comment]
Discussion from metrics standup: The lines are behind the chart, which is why we aren's seeing them. We don't want to go back to the default transparency that we are overriding. Can we look into z-indexing?

**Comment by sandikbarr** [comment]
z-indexing the line doesn't seem to help.

Here is a screenshot of adjusting the transparency to .8 with our colors, not enough contrast on some of these in my opinion. The default transparency is .5. We have it set to opacity: 1 which applies to both bar and area charts.
<img width="569" alt="screen shot 2018-01-25 at 9 59 44 am" src="https://user-images.githubusercontent.com/2250413/35398551-ce199292-01b7-11e8-9fc4-8b8908c76524.png">

Maybe also relevant since these charts become stacked bar charts when there are < 4 data points: The stacked bar chart actually does something different than the area, it puts the line in front of the data piece that you are hovering. In this example I'm hovering Secrets #2. (This is also with opacity: 0.8)
<img width="598" alt="screen shot 2018-01-25 at 10 12 34 am" src="https://user-images.githubusercontent.com/2250413/35398785-63318cfe-01b8-11e8-990c-55dcd4324bb4.png">

Side note: In these examples, I am also seeing that a minor version update to C3 must have dropped the points by default on the lines and area charts. So we'll want to get those tackled before updating metrics from the styleguide again.

**Comment by pkarman** [comment]
The fix for #159 (updating line charts) will handle some of the issues raised here, so I'm going to block this one on 159 and re-evaluate when 159 is complete.

**Comment by sandikbarr** [comment]
Dots removed from stacked charts is now deployed.

Otherwise not sure yet what I can do with the lines with the opacity. We could mess with it some more maybe with a color scheme that works with some transparency. Default transparency of 50% is _very_ transparent. The slightly transparent examples above are at 80%.

**Comment by pkarman** [comment]
@farski says let's leave it as-is for now. Closing this and will open new ticket if/when we get clearer user feedback.
