### ISSUE TITLE
should line charts become bar charts for fewer data points

### ISSUE THREAD

**Issue by sandikbarr** [PRX/metrics.prx.org#191]
Just based on my own preferences and how a single data point doesn't show very well in a chart, I made the stacked area charts show up as stacked bar charts when there are < 4 data points. I didn't do anything with line charts but am wondering if they should be displayed as bar charts, not stacked, when there are a smaller number of data points.

Is < 4 the right place to switch to bar chart?

So instead of this
![Screen Shot 2018-01-31 at 12.26.39 PM.png](https://images.zenhubusercontent.com/57ced6eee40e5714b16e5096/ca1b33b2-9bc7-42ec-a10c-9a532a8d59f2)

We'd have this
![Screen Shot 2018-01-31 at 2.41.50 PM.png](https://images.zenhubusercontent.com/57ced6eee40e5714b16e5096/d838fd3a-64db-483a-b6e2-1b3b37b1409e)

**Comment by pkarman** [comment]
I like that change, and unless @farski has strong objections, I think we should implement it for beta and then gather some user feedback on it.

**Comment by farski** [comment]
I don't think I would base any sort of change like this on total data points, (where # of data points = # of selected episodes * # of intervals in the range), as that could lead to some strange flip flopping. Three intervals with one episode would be bars, but one interval with five episodes would be lines (dots).

If the thought is to base it on the number of intervals independent of how many episodes are selected, three intervals with 10 episodes selected would be 30 bars, which seems like a lot to me.

My preference would be to use the selected chart type any time there is >1 unique x-value represented in the data. _I_ don't mind the somewhat goofy result of that (like the first screenshot) that comes with a single x-value, but I can see the appeal of to a different graph type in that specific situation. But I do think as soon as it's possible to start drawing a line or area, we should do that (ie change how the stacked area chart currently works).

That being said, I also think this is an unusual/uncommon combination of parameters to select, since it leads to so much duplication of data:

![image](https://user-images.githubusercontent.com/3483/35738458-faa01354-07fc-11e8-993e-5929977bee0a.png)

A more granular interval results in all of the data that this chart is providing remaining available in the table, but with much more information visible in the chart.

**Comment by sandikbarr** [comment]
Might seem like a goofy combination to select, but it's pretty easy to get there on accident. Load the app, select monthly from the quick selector.

**Comment by sandikbarr** [comment]
It's not new behavior, but yes the behavior that changes the area chart to a bar chart when there are less than 4 data points is in master. We do not currently have any handling for the line charts with few data points.

**Comment by sandikbarr** [comment]
There were mixed opinions on this, so in order to make things consistent, I only used bar charts when there are just 1 or 2 data points.
