### ISSUE TITLE
Discuss feature set on mobile

### ISSUE THREAD

**Issue by farski** [PRX/metrics.prx.org#28]
I think we know there is demand for good mobile support, but the marginal cost of work as we approach 100% feature parity with desktop potentially gets fairly high. Worth having a think through if that's true at all, or what we'd do if it is.

**Comment by pkarman** [comment]
Not having mobile support as part of the "beta" feature set seems like a blocker to me. Is there a strong reason for not using a responsive design so that things work on smaller screen sizes? Seems like if we know folks are going to use their pads and phones, we wouldn't want to promote the product if it does work on those devices.

**Comment by pkarman** [comment]
@farski @kookster @sandikbarr and @pkarman met to discuss. We agreed that responsive design should take mobile into account for sidebar (#130) and that we're aiming for full feature parity regardless of form factor.

We'll wait till after beta release to gather feedback on specific interactions that require some design attention on mobile devices.
