### ISSUE TITLE
Downloads Table by Publish Date

### ISSUE THREAD

**Issue by IcusFMagni** [PRX/metrics.prx.org#347]
A selectable table separate from the current Downloads view.

**Comment by sandikbarr** [comment]
related #251 and #346

**Comment by sandikbarr** [comment]
As mentioned in #251, 30 day cumulative download numbers are used to quote download numbers to sponsors. Specifically per Madeleine, is that we provide an average of this number from the most recent 6 episodes. This number is a moving target, and Madeleine has to currently pull all this together manually. It would be super helpful to them, if we could show the average total from the charted/selected/most recent episodes along with each total in the number of days range. Additionally, we talked about the chart being more useful as cumulative numbers instead of interval based as we currently have in our downloads, but it's possible users want both options.
