### ISSUE TITLE
episode selection design

### ISSUE THREAD

**Issue by sandikbarr** [PRX/metrics.prx.org#358]
Design the episode selection, exclusively for desktop view. From mobile, users will be able to get to a view of one or more selected episodes through a URL, but making the actual selections from mobile feels unnecessary. Mobile users will be able to clear the episode selection and get back to the paged episode interface. There are limitations on URL length that will put a limit on the amount of episodes that can be selected from URL, but it doesn't seem like a practical concern for the purpose of clicking an episode outlier link from an email.

On mobile, the drop date chart will have a reasonable default such as the last 10 episodes.

As users select episodes, the data will begin loading on the fly (no apply button). If that ends up feeling too cumbersome, we could apply on menu close or add an explicit apply button.

There should also be some sort of way to see the accumulation of selected episodes.

**Comment by farski** [comment]
![screen shot 2019-01-24 at 1 21 32 pm](https://user-images.githubusercontent.com/3483/51699692-67209c00-1fdb-11e9-9bae-d0fedf61eb21.jpg)
_(I don't know why that looks so dark; Chrome is messing with the file)_

[PRX Metrics.zip](https://github.com/PRX/metrics.prx.org/files/2793179/PRX.Metrics.zip)

- The `Reference` artboard in the Sketch file has some updated elements that aren't reflected in the others that show various states; when there's a discrepancy use `Reference` as reference
- Magnifying glass and Info button icons are in the sketch file as Symbols
- For specifics around padding, sizing, colors, spacing, etc, please default to consistency with the rest of the app

**Search Input**
- Searches and filters the episode list on-the-fly
- Did not include an explicit "Clear Search" button to reduce the number of widgets; but could be added if people get confused about how to get the whole list back (delete the search terms)
- Does not scroll

**List Visibility Selector**
- Inherits styles from the Daily/Monthly buttons in the date selected (active, hover, available)
- Also needs a _disabled_ state for cases where there's nothing is selected (when **Show Selected** would be disabled). Dropping the normal _available_ state color to about 40% opacity seems good, with a `not-allowed` cursor.
- If **Show Selected** is selected when the selection is cleared, it should switch back to **Show All** (same thing when the last episode that is checked becomes unchecked)
- Does not scroll

 **Episode List**
- Title are truncated; do not wrap . (full titles in tooltip)
- No search term highlighting
- Clicking on a row toggles the episode (don't need to hit the box)
- No hover state other than the `pointer` cursor
- List scrolls within the popup
- Went with unabbreviated month names since there's space; fine to abbreviate if that easier to implement since other places abbreviate
- Scroll bar in `Reference` is only there for demo purposes; not intended to be built out beyond native browser UI

**Info Button/Overlay**
- Not sure who should write copy for this; I haven't so I left the designs kind of unfinished
- Does not scroll

**Episode Counter**
- Does not scroll
- With no episodes selected, this shows the total number of episodes for the show (even if they haven't all loaded into the list yet)
- When any number of episodes are selected, the counter reduces in opacity, and a selection counter appears

**Selection Counter**
- Does not scroll
- Only visible when one or more episodes are selected
- Counts the number of checked episodes and provides a control to clear the current selection

**Done Button**
- Does not scroll
- Theoretically doesn't do anything other than dismiss the popup; since checkboxes update live

**~First-run Experience~**
- Punted
