### ISSUE TITLE
Drop day chart refinements

### ISSUE THREAD

**Issue by farski** [PRX/metrics.prx.org#386]

**Comment by farski** [comment]
Here are my recommendations on this:

1. Switch the graph the `spline`/smooth lines
1. Remove points/circles (see below)
1. Ensure that lines are ordered with newer episodes on top (Z depth)
1. Line widths (newer-to-older) `8.625`, `5.75`, `3.33`, `2.5`, `1.5`, `1.5`, `1.5`…
1. Drop the bar chart, as it's largely duplicative of the 28D chart

Right now I have no strong recommendations on the colors. I don't know that monochrome will prove itself to be the best option, but seems like a fine place to start.

2. (Cont.) To get work around cases where a series only has a single point, I think the points should still be generated by C3, but then turned off with CSS, and turned back on when there's only a single point in the series. Something along these lines:

```
#line-chart .c3-chart-line .c3-circle {
  display: none;
}

#line-chart .c3-chart-line .c3-circle:nth-last-child(1):nth-child(1) {
  display: block;
}
```

**Comment by sandikbarr** [comment]
Not sure how this would work out exactly, but I was wondering if starting the chart at 0 downloads instead of the first data point would help solve the single data point problem. Then we'd actually have a line instead of the single point. The single point doesn't show the greatest (but it did seem better than nothing with points removed.) The weird thing about it might be that the 0 downloads data point would be pre drop, so the index for that data point would be -1 (if that makes sense, seems weird.)

**Comment by brandonhundt** [comment]
@farski do you have a design/code pen I can take a look at for this? Thanks

**Comment by sandikbarr** [comment]
@brandonhundt @farski Does a screenshot help? This is with the new line widths and points CSS:
<img width="1440" alt="Screen Shot 2019-05-29 at 11 26 26 AM" src="https://user-images.githubusercontent.com/2250413/58574064-c0584080-8204-11e9-8da6-e621c3ecd9b1.png">
That single point does expand on hover:
<img width="1440" alt="Screen Shot 2019-05-29 at 11 26 15 AM" src="https://user-images.githubusercontent.com/2250413/58574091-d108b680-8204-11e9-9bd8-02d6b973a157.png">

**Comment by brandonhundt** [comment]
Thanks @sandikbarr That is very helpful. From a visual perspective I think this is looking pretty good, and I think that monochromatic works fairly well in this instance. 

That said, if the assumption is that the user wants to see how the latest episode compares to the first 28 days of previous episodes, then I would recommend making the most recent episode orange so it really stands out. 

Otherwise, this is a fine presentation in my opinion.

**Comment by farski** [comment]
Starting each line at 0 is interesting. It could work, but I think my main question is how necessary it is. The situations where _any_ episode of a show has been out for < 1 day are (generally) at most 1/7th of the time; less for a biweekly/monthly show. I think nearly every time a user interacts with this, there wouldn't be any episodes that are < 1 day old.

The other thing to consider there is that the _current_ day is incomplete data. In building out the Quicksight dashboards I'm usually very hesitant to include any incomplete data points, because it's hard to know which users will correctly interpret them. With this I think I usually haven't filtered out today, because it's cumulative and doesn't completely reset to 0, but it does lead to some weird behavior as the number slides up throughout the day.

I don't generally think of this viz as a way for someone to track day-of numbers. For me it's really about seeing the trends over a period, so I don't think we have to optimize for the edge case where something has only been out for a few hours needs to be a priority.

**Comment by sandikbarr** [comment]
except that I'd argue this drop day now becomes the "single episode chart" that we link to from publish (see #390) or elsewhere users would want to look at performance of a single episode, which I would think would often be happening on the publish date just for reassurance (at least it seemed that way in earlier user interviews.) I think they understand the data is incomplete because it's current day. Another thought- if something has only been out for a few hours, we could link users to hourly drop data.

**Comment by sandikbarr** [comment]
FYI- I pushed up that CSS to the current PR branch.

Removing the horizontal bar chart is a small logic update that I could also get in asap. Replacing it with the 28 day performance feature is obvs a bigger deal though.

**Comment by sandikbarr** [comment]
Rick also suggested rounding the lines. Looks good to me, might add this too.
```
.c3-line {
  stroke-linecap: round;
}
```
