### ISSUE TITLE
Figure out a good way to geo data

### ISSUE THREAD

**Issue by kookster** [PRX/metrics.prx.org#4]
look at options for how to display downloads by countries/states/cities - @sandikbarr has prototyped some ideas already, would be good to look at how to present this info (some kind of heat map? top N cities?)

**Comment by sandikbarr** [comment]
The prototype on geo data was not very hashed out https://prx.github.io/chart.prx.org/geography.

I did see when looking at Podtrac that they only show geo data by country, not at the city level.

**Comment by kookster** [comment]
thanks @sandikbarr 
I have seen requests for city level from our own team, esp. for when we plan events and tours, interesting to think about how to do that - drill down?

**Comment by pkarman** [comment]
@sandikbarr should this go back on the backlog for possible inclusion in next sprint?

**Comment by sandikbarr** [comment]
@pkarman I would be more inclined to vote for closing since I did it last "sprint." If further work is needed, we should create a more specific ticket, like reconciling the data with the regions GeoChart wants, or taking a different approach with a different mapping library if we discover GeoChart does not meet our needs.
