### ISSUE TITLE
Design date and time selection

### ISSUE THREAD

**Issue by sandikbarr** [PRX/metrics.prx.org#80]
Provide designs for what data and time selection looks like and describe how users interact with controls

**Comment by sandikbarr** [comment]
What values go in the "Last 28 days" standard range dropdown? If the user chooses custom dates that do not match one of the standard ranges provided, what is shown as selected, "Custom"?

**Comment by farski** [comment]
_(Including some details about the interval selector in here, because it has a close relationship to the date range selector)_

There are thee main controls for dealing with date range and charting intervals:

- Interval quick selector
- Date range presets quick selector
- Advanced range and interval panel

The two quick selectors apply their changes immediately after the user makes a selection (ie no apply button needed).

The **interval selector** can look fairly similar to the current implementation. I think it'd be good to drop the checkboxes for single-select UI controls.
<img width="311" alt="screen shot 2017-12-12 at 9 34 23 am" src="https://user-images.githubusercontent.com/3483/33889929-b2423eb2-df1f-11e7-987c-d0fc686c9a89.png">
The text in the control button reflects what is currently true for the chart.

The **date range preset selector** includes a set of useful/frequently used date ranges that can be applied instantly. The dropdown includes a text description of each range (eg *Last month*), and a bit of informational date data so it's always obvious what the range actually represents (ie, for *This week* it includes the fact that we start weeks on a given day of the week). The options are loosely arranged into logical groupings.

The text in the control button includes just the short text description of the current range. In cases where the current range doesn't match one of the options, the button would indicate the actual current range (by date, eg _Nov 13, 2017 – Nov 18, 2017_).
<img width="684" alt="screen shot 2017-12-12 at 9 51 33 am" src="https://user-images.githubusercontent.com/3483/33890725-0e718f2e-df22-11e7-9186-bc7eab48ecc5.png">

The **advanced range selector** allows for the selection of an arbitrary date range. Any time the popup goes from being not displayed to displayed, it should reflect the current state of the app. Even in cases where the current range matches one of the presets, there is no active/highlighted state for the preset selectors in the popup. The beginning and ending date of the range are selected through calendar widgets, or through inputting dates in text fields. The popup also includes an interval selector.

The calendar widgets should always show the month of the currently selected day for each terminal of the range. The selected day is highlighted; the range is not. The user can scroll through months of each widget independently.

When changes are made to selections in the popup, they are not applied immediately. Instead, they are applied all at once when the user applies them, which dismisses the popup and invokes the changes.

Clicking outside the bounds of the popup dismisses the popup and trashes any changes.
<img width="921" alt="screen shot 2017-12-12 at 10 02 55 am" src="https://user-images.githubusercontent.com/3483/33891341-a53cf14a-df23-11e7-88ab-37c88edfda4f.png">

**Comment by sandikbarr** [comment]
In the date range preset selector, what does the "Other..." option do?

**Comment by sandikbarr** [comment]
Am I correct in thinking that the advanced range selector covers the menu(?) bar when open but the quick selectors do not?

**Comment by sandikbarr** [comment]
Are we introducing drop shadows to modal type components now? We have been decidedly flat with other modals and pop ups, but I've noticed we do have a drop shadow on the `prx-select` dropdown (not sure if that was intentional or came out of the box.)

**Comment by sandikbarr** [comment]
Grammar wise, I think day of the week should be separated from month with a comma, same for day of month and year. Are we intentionally not including commas in the date formats?

**Comment by farski** [comment]
>In the date range preset selector, what does the "Other..." option do?

I was thinking it could just bring up the advanced panel. Could also be labeled _Custom…_ or _Advanced…_ or something along those lines.

> Am I correct in thinking that the advanced range selector covers the menu(?) bar when open but the quick selectors do not?

I wouldn't say I did that on purpose. I could see hiding some of the buttons when the advanced panel is visible makes that whole area a little less cluttered, but if it feels weird to have different popups coming up at different depths I'd just make them all come up below the toolbar

> Are we introducing drop shadows to modal type components now? We have been decidedly flat with other modals and pop ups, but I've noticed we do have a drop shadow on the prx-select dropdown (not sure if that was intentional or came out of the box.)

All the popups I was seeing in metrics at the moment (multi selects, calendars, chart hovers) had shadows, so I included them. I defer to you to do whatever is consistent with previous decisions.

> Grammar wise, I think day of the week should be separated from month with a comma, same for day of month and year. Are we intentionally not including commas in the date formats?

I think we're going to end up with slightly different ways of representing dates in different contexts. The way we present a date in the range presets, where they're just secondary metadata and space is at a premium, is different than in the range summary, or the date range text inputs. In the case of the presets I didn't include a comma because there are so few options with day-of-week labels, so the whole thing looked a bit more consistent without them (or I should say, it looked somewhat inconsistent/random with them). In general, I think we continue to use the standard way of presenting dates (with commas). If you prefer to have the commas in this case as well and it doesn't make the design feel off to you, that's fine.
