### ISSUE TITLE
Replace beta notice in footer

### ISSUE THREAD

**Issue by farski** [PRX/metrics.prx.org#86]
We could put a more apt beta notice in the footer. Something specific to metrics, and remove the language about prx.org proper

**Comment by sandikbarr** [comment]
Should the metrics app not use the footer from the styleguide, does the styleguide footer need to be updated to support a more specific beta notice, or will a separate metrics beta notice suffice?

**Comment by pkarman** [comment]
Let's do a separate metrics-specific beta notice.

**Comment by sandikbarr** [comment]
@farski If we're doing a separate notice for metrics, please provide design input for beta notice and footer in general. I'll have to replace the whole footer (which means more than 2 points here.)

**Comment by farski** [comment]
I'm not particularly concerned about outwardly calling this a beta too much, given how many people will actually be seeing it

I'd be happy if this copy just disappears. The feedback link in there doesn't even work for me, and "use old version" doesn't apply. I will defer to @kookster about how much beta messaging we want to do.

![image](https://user-images.githubusercontent.com/3483/35296212-583fe8d8-0049-11e8-98f2-fc386e791acc.png)

**Comment by sandikbarr** [comment]
I would say that those same concerns apply to this footer as it is used in Publish.

**Comment by pkarman** [comment]
Then this sounds like the styleguide footer needs to change, and the metrics release is the catalyst.

@kookster - can you give us some marketing guidance? My 2c: remove the whole thing.

**Comment by kookster** [comment]
yeah, agreed, this beta and old version language doesn't need to be in the footer, and seems like publish and metrics would benefit from having it removed.

For the link to give feedback, we have a different ticket about having a zendesk widget on the page, #181, so that should go from the footer.

I would say remove that stuff on the left side of the footer, and we'll have another crack at updating this later with something more useful, like after the corporate site build where we'll be thinking about footer content again.
