### ISSUE TITLE
Chart overlay can obstruct the graph

### ISSUE THREAD

**Issue by farski** [PRX/metrics.prx.org#88]
When active for data points on the right side of the chart, the overlay can obstruct the graph

![screen shot 2017-11-28 at 9 11 51 am](https://user-images.githubusercontent.com/3483/33324012-381dda8c-d41c-11e7-8ce7-537e3ea73fdc.png)

**Comment by sandikbarr** [comment]
Controlling where the tooltip is rendered is going to be a helluva trick to pull off. It's possible, but we have to also know where in the chart area it can be rendered that won't cover the graph. http://c3js.org/reference.html#tooltip-position Putting that kind of work in when our intention is to replace the charting library seems kinda wrong.

Another option that may partially address this is to not group the tooltip so that only the value for the point that is hovered on is shown: http://c3js.org/samples/tooltip_grouped.html

**Comment by sandikbarr** [comment]
to be used to evaluate chart solution
